### ISSUE TITLE
Images in first column are tiny

### ISSUE THREAD

**Issue by nicholaswilson100** [sakaicontrib/mneme-project#2]
look at first mneme screen, you may have to create a test first. Check any images in first column are 'normal size'

**Comment by buckett** [comment]
Fixed through #3

**Comment by buckett** [comment]
This is the problem of the icons not appearing at the correct size:
<img width="96" alt="screen shot 2017-10-06 at 09 53 17" src="https://user-images.githubusercontent.com/5921/31270432-4686cc2e-aa7c-11e7-8318-f4ab4d0aa08d.png">
