### ISSUE TITLE
Migration script for Sakai 11.x adds columns but no default value when required, breaking mneme.

### ISSUE THREAD

**Issue by jbrokamp** [sakaicontrib/mneme-project#6]
When using the migration script **mneme_assessment_oxford.sql**, it adds a column `SEND_SUBMIT_EMAIL` to the `MNEME_ASSESSMENT` table. However, if there are already assessments present added by a previous version of mneme, the value will become `null` in this column.

This has the unfortunate effect that an error page is shown when opening mneme from Sakai. The page shows a non descriptive message and a button that seemingly does nothing.

> Alert
>
> Press "Return" to continue.
>
> Return

There is no cause of the error provided. After code inspection it turns out that a check on the `sendEmailOnSubmission` setter of the `AssessmentImpl` object makes sure that an `IllegalArgumentException` is thrown when the value returns `null` from the database.

@bgarciaentornos @buckett I've added a pull request to this issue to fix the migration script by adding a default value for that column.

**Comment by buckett** [comment]
Thanks for this.
